### Site info:
title: コケいろの雑記
tagline: とりとめのないメモメモメモメモ
author: kokeiro
email: kokeiro.ssbm.001@gmail.com
description: "コケいろの雑記。ブログ。" # You can edit this line in _config.yml. It will appear in your document head meta and in your feed.xml site description
keywords: "kokeio"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
#baseurl: "/freshman21" # the subpath of your site, e.g. /blog/
#url: "http://yulijia.net/freshman21" # the base hostname & protocol for your site
locale: jp_JP

### Personal info and site tools info:
twitter_username: kokeiro0_00
github_username:  kokeiro001
disqus_shortname: kokeiro0_01
favicon:     "/images/favicon.ico"
aboutme: コケいろ。ゲームプログラマ。お酒とプログラミングとエロゲとC#が好き。 # these are shown on aboutme-sidebar.
aboutme_photo: "/images/self.jpg"
google_analytics_key: UA-78749869-1 # put YOUR key here to enable tracking! (blank to disable)


### Site setting:
ShowContactInfo: "True" # Personal Info (twitter,github,email) can be seen on aboutme-sidebar, those info only shown where ShowContactInfo == True
default_column: "two" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "jp" # blog sidebar language set, only include: English(en) and Chinese (cn)

locales:
    en:
      Aboutme: "About Me"
      Archives: "Archives"
      Blogroll: "Blogroll"
      Categories: "Categories"
      Copyright_Notice: "Copyright Notice"
      Recent_Posts: "Recent Posts"
      Tags: "Tags"
      Previous: "Older"
      Next: "Newer"
      PostedInCategories: "Posted in"
      Taggedwith: "and tagged"
      PostDate: "on "
      Google_search: "Site Search"
    cn:
      Aboutme: "关于我"
      Archives: "存档"
      Blogroll: "良师益友"        
      Categories: "分类目录"    
      Copyright_Notice: "版权声明"
      Recent_Posts: "近期文章"
      Tags: "标签" 
      Previous: "前一页"
      Next: "后一页"
      PostedInCategories: "目录:"   
      Taggedwith: "| 标签:"
      PostDate: "| 发表时间: "
      Google_search: "站内搜索"
    jp:
      Aboutme: "著者"
      Archives: "アーカイブ"
      Blogroll: "ブログロール"
      Categories: "カテゴリー"
      Copyright_Notice: "Copyright Notice"
      Recent_Posts: "最近の投稿"
      Tags: "タグ"
      Previous: "前の記事"
      Next: "次の記事"
      PostedInCategories: "カテゴリー："
      Taggedwith: "タグ："
      PostDate: "| 投稿日時 "
      Google_search: "サイト内検索"

### your Blogroll info, only name can shown on the page.

Blogroll:
      - name: コケいろ
        href: https://kokeiro001.github.io/
        title: コケいろの雑記。

### Build settings
markdown: kramdown

#highlighter: pygments
kramdown:
        input: GFM
        syntax_highlighter: rouge
gems: [jekyll-paginate]
paginate: 5
excerpt_separator: <!-- more -->
